services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: david
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped
  davydray-api:
   container_name: davydray-api
   image: davydray/customer_management-api
   environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/amigoscode
   ports:
    - "8088:8080"
   networks:
    - postgres
   depends_on:
    - db
   restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: